/**
 * The variant field registry — the transcription of the entity spec's field table
 * (`.inspire_kb/04_domain/analytics/variant/analytics.variant.md` → ## Fields).
 *
 * It is the single place the field allow-list lives. Everything that needs to know
 * which fields exist derives from it: query validation (the security boundary), the
 * ClickHouse parameter types used to bind values, the table DDL, and the GraphQL
 * `VariantField` enum — per adr-graphql-query-transport, which forbids a second
 * hand-maintained copy of the allow-list.
 */

/** A field's storage type and the ClickHouse type its values bind as. */
export interface VariantFieldSpec {
  /** The declared ClickHouse column type, verbatim from the entity spec. */
  readonly chType: string;
  /** The type a bound query parameter uses (wrappers stripped). */
  readonly bindType: string;
  /** True when the column stores an array of `bindType`. */
  readonly array?: boolean;
}

export const VARIANT_FIELDS = {
  id: { chType: 'UUID', bindType: 'UUID' },
  project_id: { chType: 'UInt64', bindType: 'UInt64' },
  created_at: { chType: 'DateTime64(3)', bindType: 'DateTime64(3)' },
  version_date: { chType: 'DateTime64(3)', bindType: 'DateTime64(3)' },
  uri: { chType: 'String', bindType: 'String' },
  origin: { chType: 'LowCardinality(String)', bindType: 'String' },
  type: { chType: 'LowCardinality(String)', bindType: 'String' },
  collection: { chType: 'String', bindType: 'String' },
  hpo: { chType: 'Array(String)', bindType: 'String', array: true },
  score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  allele_frequency: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  user_id: { chType: 'Nullable(UInt64)', bindType: 'UInt64' },
  annotation_version: { chType: 'Nullable(String)', bindType: 'String' },
  trio_variant_category: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  trio_category_tag: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  ind1_zygosity: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  ind1_vaf: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  ind1_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  ind2_zygosity: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  ind2_vaf: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  ind2_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  ind3_zygosity: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  ind3_vaf: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  ind3_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pos_genome: { chType: 'Nullable(String)', bindType: 'String' },
  pos_chr: { chType: 'Nullable(String)', bindType: 'String' },
  pos_position: { chType: 'Nullable(UInt64)', bindType: 'UInt64' },
  pos_id: { chType: 'Nullable(String)', bindType: 'String' },
  pos_sv_end: { chType: 'Nullable(UInt64)', bindType: 'UInt64' },
  pos_sv_len: { chType: 'Nullable(Int64)', bindType: 'Int64' },
  pos_sb: { chType: 'Nullable(String)', bindType: 'String' },
  pos_seg_dup: { chType: 'Nullable(String)', bindType: 'String' },
  pos_chrom_band: { chType: 'Nullable(String)', bindType: 'String' },
  pos_microsat: { chType: 'Nullable(String)', bindType: 'String' },
  gt_allele_ref: { chType: 'Nullable(String)', bindType: 'String' },
  gt_allele_alt: { chType: 'Nullable(String)', bindType: 'String' },
  gt_allele_num: { chType: 'Nullable(String)', bindType: 'String' },
  gt_allele: { chType: 'Nullable(String)', bindType: 'String' },
  gt_calc_genotype: { chType: 'Nullable(String)', bindType: 'String' },
  gt_zyg: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  gt_aa: { chType: 'Nullable(String)', bindType: 'String' },
  gt_ac: { chType: 'Nullable(String)', bindType: 'String' },
  gt_af: { chType: 'Nullable(String)', bindType: 'String' },
  gt_an: { chType: 'Nullable(Int64)', bindType: 'Int64' },
  gt_cigar: { chType: 'Nullable(String)', bindType: 'String' },
  gt_db: { chType: 'Nullable(String)', bindType: 'String' },
  gt_end: { chType: 'Nullable(String)', bindType: 'String' },
  gt_h2: { chType: 'Nullable(String)', bindType: 'String' },
  gt_h3: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_gt: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_ft: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_gl: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_gle: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_pl: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_gp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  gt_format_gq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  gt_format_hq: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_ps: { chType: 'Nullable(Int64)', bindType: 'Int64' },
  gt_format_pq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  gt_format_ec: { chType: 'Nullable(String)', bindType: 'String' },
  gt_format_mq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  gt_technique: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  call_filter: { chType: 'Nullable(String)', bindType: 'String' },
  call_quality: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_read_depth_ref: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_read_pct_ref: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_read_depth_alt: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_read_pct_alt: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_read_depth: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_bq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_mq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_mq0: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_ns: { chType: 'Nullable(String)', bindType: 'String' },
  call_format_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_sv_cipos: { chType: 'Nullable(String)', bindType: 'String' },
  call_sv_ciend: { chType: 'Nullable(String)', bindType: 'String' },
  call_sv_cilen: { chType: 'Nullable(String)', bindType: 'String' },
  call_sv_dp: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_sv_dpadj: { chType: 'Nullable(String)', bindType: 'String' },
  call_fold_change: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  call_roq: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  exist_existing_variation: { chType: 'Nullable(String)', bindType: 'String' },
  exist_somatic: { chType: 'Nullable(String)', bindType: 'String' },
  exist_clin_sig: { chType: 'Nullable(String)', bindType: 'String' },
  exist_pheno: { chType: 'Nullable(String)', bindType: 'String' },
  exist_dbsnp: { chType: 'Nullable(String)', bindType: 'String' },
  exist_cosmic: { chType: 'Nullable(String)', bindType: 'String' },
  exist_hgmd: { chType: 'Nullable(String)', bindType: 'String' },
  exist_others: { chType: 'Nullable(String)', bindType: 'String' },
  exist_dbsnp_id: { chType: 'Nullable(String)', bindType: 'String' },
  exist_dbsnp_rs: { chType: 'Nullable(String)', bindType: 'String' },
  exist_dbsnp_rs_url: { chType: 'Array(String)', bindType: 'String', array: true },
  exist_dbsnp_ssr: { chType: 'Nullable(String)', bindType: 'String' },
  exist_ensdgv: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_url: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_clnsig: { chType: 'Array(String)', bindType: 'String', array: true },
  clin_clinvar_clnsig_str: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_clnrevstat: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_clndn: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_clnsigconf: { chType: 'Nullable(String)', bindType: 'String' },
  clin_acmg: { chType: 'LowCardinality(Nullable(String))', bindType: 'String' },
  clin_gene_pheno: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clinvar_cnv: { chType: 'Nullable(String)', bindType: 'String' },
  clin_dbvar_path_dup: { chType: 'Nullable(String)', bindType: 'String' },
  clin_dbvar_path_del: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_variant_id: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_mp_name: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_mp_score: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_entity_significance: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_entity_disease: { chType: 'Nullable(String)', bindType: 'String' },
  clin_civic_entity_therapies: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clngen_cat: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clngen_met: { chType: 'Nullable(String)', bindType: 'String' },
  clin_clngen_not_met: { chType: 'Nullable(String)', bindType: 'String' },
  clin_intogen: { chType: 'Nullable(String)', bindType: 'String' },
  clin_cv_score: { chType: 'Nullable(String)', bindType: 'String' },
  clin_cv_classification: { chType: 'Nullable(String)', bindType: 'String' },
  clin_medgen_id: { chType: 'Nullable(String)', bindType: 'String' },
  clin_medgen_disease: { chType: 'Nullable(String)', bindType: 'String' },
  clin_medgen_disease_url: { chType: 'Array(String)', bindType: 'String', array: true },
  clin_franklin: { chType: 'Nullable(String)', bindType: 'String' },
  clin_franklin_url: { chType: 'Nullable(String)', bindType: 'String' },
  clin_disease_omim_orphanet: { chType: 'Nullable(String)', bindType: 'String' },
  pred_sift_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_enspolyphen_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_revel_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_refpolyphen_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_lrt_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_mutationtaster_score: { chType: 'Nullable(String)', bindType: 'String' },
  pred_mutationassessor_score: { chType: 'Nullable(String)', bindType: 'String' },
  pred_fathmm_score: { chType: 'Nullable(String)', bindType: 'String' },
  pred_fathmm_mkl_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_metasvm_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_metalr_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_gerp_rs: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_phylop_mammalian: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_siphy_29way: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_cadd_raw: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_dann_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_eigen_raw_coding: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_genocanyon_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_ada_score: { chType: 'Nullable(String)', bindType: 'String' },
  pred_rf_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_alphamissense_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_alphamissense_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_bayesdel_addaf_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_bayesdel_addaf_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_bayesdel_noaf_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_cadd_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_cadd_phred_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_carol_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_carol_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_clinpred_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_clinpred_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_dann_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_eve_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_eve_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_loftool_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_metalr_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_metarnn_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_metarnn_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_polyphen_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_primateai_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_primateai_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_revel_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_sift_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spadahc_sum: { chType: 'Nullable(String)', bindType: 'String' },
  pred_spliceai_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_spliceai_ag: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_al: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dg: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dl: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_vest4_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_vest4_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_gerp_prediction: { chType: 'Nullable(String)', bindType: 'String' },
  pred_exomiser_variant_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_ds_ag: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_ds_al: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_ds_dg: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_ds_dl: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dp_ag: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dp_al: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dp_dg: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_spliceai_dp_dl: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  pred_mitomap_mtscore: { chType: 'Nullable(String)', bindType: 'String' },
  pred_mitomap_quartile: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_max_af: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_max_af_pops: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_1kg_all: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_1kg_afr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_1kg_amr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_1kg_eas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_1kg_eur: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_1kg_sas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_afr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_amr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_asj: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_eas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_fin: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_nfe: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_oth: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomade_sas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_afr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_ami: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_amr: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_asj: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_eas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_fin: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_mid: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_nfe: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_oth: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomadg_sas: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomad_sv_evidence: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_gnomad_sv_svtype: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_gnomad_sv_af: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_gnomad_mito_ac_hom: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomad_mito_af_hom: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomad_mito_ac_het: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_gnomad_mito_af_het: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  popaf_exac_af: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_exac_an: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_exac_ac: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_exac_ac_hemi: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_exac_ac_het: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_exac_ac_homo: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_gnomad_id: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_gnomad_id_url: { chType: 'Nullable(String)', bindType: 'String' },
  popaf_pli_gene_score: { chType: 'Nullable(Float64)', bindType: 'Float64' },
  gene_ensembl_gene: { chType: 'Nullable(String)', bindType: 'String' },
  gene_symbol: { chType: 'Nullable(String)', bindType: 'String' },
  gene_symbol_source: { chType: 'Nullable(String)', bindType: 'String' },
  gene_hgnc_id: { chType: 'Nullable(String)', bindType: 'String' },
  gene_hgnc_id_url: { chType: 'Nullable(String)', bindType: 'String' },
  feat_consequence: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_consequence: { chType: 'Nullable(String)', bindType: 'String' },
  feat_variant_class: { chType: 'Nullable(String)', bindType: 'String' },
  feat_feature: { chType: 'Nullable(String)', bindType: 'String' },
  feat_feature_url: { chType: 'Nullable(String)', bindType: 'String' },
  feat_feature_type: { chType: 'Nullable(String)', bindType: 'String' },
  feat_canonical: { chType: 'Nullable(String)', bindType: 'String' },
  feat_strand: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_hgvsc: { chType: 'Nullable(String)', bindType: 'String' },
  feat_hgvsc: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_hgvsp: { chType: 'Nullable(String)', bindType: 'String' },
  feat_hgvsg: { chType: 'Nullable(String)', bindType: 'String' },
  feat_hgvs_offset: { chType: 'Nullable(String)', bindType: 'String' },
  feat_spdi: { chType: 'Nullable(String)', bindType: 'String' },
  feat_vrs: { chType: 'Nullable(String)', bindType: 'String' },
  feat_impact: { chType: 'Nullable(String)', bindType: 'String' },
  feat_biotype: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_exon: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_intron: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_cdna_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_cds_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_protein_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_amino_acids: { chType: 'Nullable(String)', bindType: 'String' },
  feat_codons: { chType: 'Nullable(String)', bindType: 'String' },
  feat_distance: { chType: 'Nullable(String)', bindType: 'String' },
  feat_flags: { chType: 'Nullable(String)', bindType: 'String' },
  feat_pubmed: { chType: 'Nullable(String)', bindType: 'String' },
  feat_pubmed_url: { chType: 'Array(String)', bindType: 'String', array: true },
  feat_custom_annotation: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_feature: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_feature_url: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_feature_type: { chType: 'Nullable(String)', bindType: 'String' },
  feat_ens_canonical: { chType: 'Nullable(String)', bindType: 'String' },
  feat_hgvsp: { chType: 'Nullable(String)', bindType: 'String' },
  feat_exon: { chType: 'Nullable(String)', bindType: 'String' },
  feat_intron: { chType: 'Nullable(String)', bindType: 'String' },
  feat_cdna_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_cds_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_protein_position: { chType: 'Nullable(String)', bindType: 'String' },
  feat_target_gene: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_omim_id: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_omim_id_url: { chType: 'Array(String)', bindType: 'String', array: true },
  extdb_swissprot: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_trembl: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_uniparc: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_uniprot_isoform: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_orphanet: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_orphanet_url: { chType: 'Array(String)', bindType: 'String', array: true },
  extdb_go: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_lovd: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_gtex: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_gtex_url: { chType: 'Nullable(String)', bindType: 'String' },
  extdb_cpic: { chType: 'Nullable(String)', bindType: 'String' },
} as const satisfies Record<string, VariantFieldSpec>;

export type VariantFieldName = keyof typeof VARIANT_FIELDS;

/** Ordered field names — the DDL column order and the GraphQL enum order. */
export const VARIANT_FIELD_NAMES = Object.keys(VARIANT_FIELDS) as VariantFieldName[];

export function isVariantField(field: string): field is VariantFieldName {
  return Object.prototype.hasOwnProperty.call(VARIANT_FIELDS, field);
}

export function variantFieldSpec(field: VariantFieldName): VariantFieldSpec {
  return VARIANT_FIELDS[field];
}
